// <auto-generated />
using LearnVocabulary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnVocabulary.Migrations
{
    [DbContext(typeof(LearnContext))]
    [Migration("20240214003136_InitialSecondMig")]
    partial class InitialSecondMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnVocabulary.Models.Definition", b =>
                {
                    b.Property<int>("DefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DefinitionId"));

                    b.Property<string>("DefinitionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeaningId")
                        .HasColumnType("int");

                    b.HasKey("DefinitionId");

                    b.HasIndex("MeaningId");

                    b.ToTable("Definitions");
                });

            modelBuilder.Entity("LearnVocabulary.Models.Meaning", b =>
                {
                    b.Property<int>("MeaningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeaningId"));

                    b.Property<string>("Antonyms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Synonyms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("MeaningId");

                    b.HasIndex("WordId");

                    b.ToTable("Means");
                });

            modelBuilder.Entity("LearnVocabulary.Models.Phonetic", b =>
                {
                    b.Property<int>("PhoneticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhoneticId"));

                    b.Property<string>("Audio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("PhoneticId");

                    b.HasIndex("WordId");

                    b.ToTable("Phonetics");
                });

            modelBuilder.Entity("LearnVocabulary.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordId"));

                    b.Property<string>("WordText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WordId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("LearnVocabulary.Models.Definition", b =>
                {
                    b.HasOne("LearnVocabulary.Models.Meaning", "Meaning")
                        .WithMany("Definitions")
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meaning");
                });

            modelBuilder.Entity("LearnVocabulary.Models.Meaning", b =>
                {
                    b.HasOne("LearnVocabulary.Models.Word", "Word")
                        .WithMany("Meanings")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("LearnVocabulary.Models.Phonetic", b =>
                {
                    b.HasOne("LearnVocabulary.Models.Word", "Word")
                        .WithMany("Phonetics")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("LearnVocabulary.Models.Meaning", b =>
                {
                    b.Navigation("Definitions");
                });

            modelBuilder.Entity("LearnVocabulary.Models.Word", b =>
                {
                    b.Navigation("Meanings");

                    b.Navigation("Phonetics");
                });
#pragma warning restore 612, 618
        }
    }
}
